import type { UserTransaction, SystemLog, UserActivity } from "@/lib/types";

// ─── Nav groups ───────────────────────────────────────────────────────────────
import {
  Boxes,
  Building2,
  ClipboardList,
  LayoutDashboard,
  Receipt,
  Settings2,
  ShoppingCart,
  Users,
} from "lucide-react";

export const navGroups = [
  {
    label: "Workspace",
    items: [
      {
        href: "/dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        roles: ["admin"],
      },
      {
        href: "/pos",
        label: "POS Register",
        icon: ShoppingCart,
        roles: ["cashier"],
      },
      {
        href: "/review",
        label: "Review",
        icon: ClipboardList,
        roles: ["cashier", "admin"],
      },
      {
        href: "/inventory",
        label: "Inventory",
        icon: Boxes,
        roles: ["admin", "frontdesk"],
      },
      {
        href: "/supplier",
        label: "Supplier",
        icon: Building2,
        roles: ["admin", "frontdesk"],
      },
      {
        href: "/procurement",
        label: "Procurement",
        icon: ShoppingCart,
        roles: ["admin", "frontdesk"],
      },
      {
        href: "/wholesale",
        label: "Wholesale",
        icon: Receipt,
        roles: ["admin", "frontdesk"],
      },
    ],
  },
  {
    label: "Administration",
    items: [
      {
        href: "/system-ad",
        label: "System Administration",
        icon: Settings2,
        roles: ["admin"],
      },
      {
        href: "/user-management",
        label: "User Management",
        icon: Users,
        roles: ["admin"],
      },
    ],
  },
];

// ─── Route helpers ────────────────────────────────────────────────────────────

export function getAllowedHrefs(role: string) {
  return navGroups
    .flatMap((g) => g.items)
    .filter((item) => item.roles.includes(role))
    .map((item) => item.href);
}

export function getDefaultRoute(role: string) {
  return getAllowedHrefs(role)[0] ?? "/login";
}

// ─── Mock product / supplier / PO data ───────────────────────────────────────

export const products = [
  {
    id: "p1",
    name: "Paracetamol 500mg",
    sku: "MED-0421",
    category: "Pain relief",
    stock: 120,
    reorder: 40,
    price: "₱5.00",
    status: "Available",
  },
  {
    id: "p2",
    name: "Amoxicillin 500mg",
    sku: "MED-0184",
    category: "Antibiotics",
    stock: 8,
    reorder: 30,
    price: "₱12.00",
    status: "Low stock",
  },
  {
    id: "p3",
    name: "Vitamin C 1000mg",
    sku: "VIT-0223",
    category: "Vitamins",
    stock: 0,
    reorder: 25,
    price: "₱8.00",
    status: "Out of stock",
  },
  {
    id: "p4",
    name: "Cough relief syrup",
    sku: "MED-0552",
    category: "Respiratory",
    stock: 63,
    reorder: 20,
    price: "₱145.00",
    status: "Available",
  },
  {
    id: "p5",
    name: "Cetirizine 10mg",
    sku: "MED-0350",
    category: "Allergy",
    stock: 36,
    reorder: 18,
    price: "₱7.50",
    status: "Available",
  },
  {
    id: "p6",
    name: "Skin cream 30g",
    sku: "DER-0108",
    category: "Dermatology",
    stock: 12,
    reorder: 15,
    price: "₱220.00",
    status: "Low stock",
  },
];

export const suppliers = [
  {
    name: "Southstar Distribution",
    code: "SSD-104",
    contact: "Mia Villanueva",
    orders: 18,
    value: "₱482,500",
    status: "Preferred",
  },
  {
    name: "Mercury Health Partners",
    code: "MHP-221",
    contact: "Paolo Garcia",
    orders: 12,
    value: "₱218,450",
    status: "Preferred",
  },
  {
    name: "Wellness Direct PH",
    code: "WDP-308",
    contact: "Anika Lim",
    orders: 7,
    value: "₱94,800",
    status: "Review",
  },
  {
    name: "CuraMed Trading",
    code: "CMT-419",
    contact: "Noah Tan",
    orders: 4,
    value: "₱45,320",
    status: "On hold",
  },
];

export const purchaseOrders = [
  {
    id: "PO-24018",
    supplier: "Southstar Distribution",
    date: "Aug 18, 2026",
    items: 14,
    value: "₱38,420",
    status: "In transit",
  },
  {
    id: "PO-24017",
    supplier: "Mercury Health Partners",
    date: "Aug 17, 2026",
    items: 9,
    value: "₱21,850",
    status: "Received",
  },
  {
    id: "PO-24016",
    supplier: "Wellness Direct PH",
    date: "Aug 16, 2026",
    items: 22,
    value: "₱45,600",
    status: "Pending approval",
  },
  {
    id: "PO-24015",
    supplier: "Southstar Distribution",
    date: "Aug 15, 2026",
    items: 11,
    value: "₱16,740",
    status: "Received",
  },
];

export const movementFast = [
  { name: "Paracetamol 500mg", units: 250 },
  { name: "Vitamin C 1000mg", units: 180 },
  { name: "Cough relief syrup", units: 145 },
];

export const movementSlow = [
  { name: "Antacid chewables", units: 12 },
  { name: "Vitamin B Complex", units: 8 },
  { name: "Skin cream 30g", units: 5 },
];

export const cashMismatches = [
  {
    date: "Aug 18",
    shift: "Morning",
    expected: "₱25,450",
    recorded: "₱24,950",
    difference: "-₱500",
    type: "short",
  },
  {
    date: "Aug 17",
    shift: "Evening",
    expected: "₱31,200",
    recorded: "₱32,200",
    difference: "+₱1,000",
    type: "over",
  },
];

// ─── System Administration mock data ─────────────────────────────────────────

export const initialTransactionsData: UserTransaction[] = [
  {
    id: 1,
    transactionNumber: "TRX-0001",
    dateTime: "Sept. 1, 2026 – 9:00 AM",
    user: "Maria Santos",
    businessType: "Retail",
    customer: "Walk-in Customer",
    total: "₱450.00",
    subtotal: "₱401.79",
    discount: "₱0.00",
    vat: "₱48.21",
    amountReceived: "₱500.00",
    change: "₱50.00",
    payment: "Cash",
    status: "Completed",
    items: [
      { product: "Paracetamol 500mg", quantity: 2, unitPrice: "₱10.00", subtotal: "₱20.00" },
      { product: "Vitamin C 1000mg", quantity: 1, unitPrice: "₱150.00", subtotal: "₱150.00" },
      { product: "Cough Relief Syrup", quantity: 1, unitPrice: "₱280.00", subtotal: "₱280.00" },
    ],
  },
  {
    id: 2,
    transactionNumber: "TRX-0002",
    dateTime: "Sept. 1, 2026 – 9:15 AM",
    user: "John Cruz",
    businessType: "Wholesale",
    customer: "ABC Pharmacy",
    total: "₱5,250.00",
    subtotal: "₱4,687.50",
    discount: "₱250.00",
    vat: "₱562.50",
    amountReceived: "₱5,250.00",
    change: "₱0.00",
    payment: "GCash",
    status: "Completed",
    items: [
      { product: "Amoxicillin 500mg (Box of 100s)", quantity: 5, unitPrice: "₱650.00", subtotal: "₱3,250.00" },
      { product: "Cetirizine 10mg (Box of 100s)", quantity: 4, unitPrice: "₱500.00", subtotal: "₱2,000.00" },
    ],
  },
  {
    id: 3,
    transactionNumber: "TRX-0003",
    dateTime: "Sept. 1, 2026 – 9:30 AM",
    user: "Maria Santos",
    businessType: "Retail",
    customer: "Walk-in Customer",
    total: "₱320.00",
    subtotal: "₱285.71",
    discount: "₱0.00",
    vat: "₱34.29",
    amountReceived: "₱320.00",
    change: "₱0.00",
    payment: "Cash",
    status: "Voided",
    items: [
      { product: "Mefenamic Acid 500mg", quantity: 4, unitPrice: "₱30.00", subtotal: "₱120.00" },
      { product: "Antacid Chewables Bottle", quantity: 1, unitPrice: "₱200.00", subtotal: "₱200.00" },
    ],
  },
  {
    id: 4,
    transactionNumber: "TRX-0004",
    dateTime: "Sept. 1, 2026 – 10:05 AM",
    user: "Maria Santos",
    businessType: "Retail",
    customer: "Walk-in Customer",
    total: "₱1,280.00",
    subtotal: "₱1,142.86",
    discount: "₱50.00",
    vat: "₱137.14",
    amountReceived: "₱1,500.00",
    change: "₱220.00",
    payment: "Cash",
    status: "Completed",
    items: [
      { product: "Multivitamins + Minerals (30s)", quantity: 2, unitPrice: "₱450.00", subtotal: "₱900.00" },
      { product: "Digital Thermometer", quantity: 1, unitPrice: "₱380.00", subtotal: "₱380.00" },
    ],
  },
  {
    id: 5,
    transactionNumber: "TRX-0005",
    dateTime: "Sept. 1, 2026 – 11:20 AM",
    user: "John Cruz",
    businessType: "Wholesale",
    customer: "St. Jude Medical Clinic",
    total: "₱18,450.00",
    subtotal: "₱16,473.21",
    discount: "₱1,000.00",
    vat: "₱1,976.79",
    amountReceived: "₱18,450.00",
    change: "₱0.00",
    payment: "30-Day Terms",
    status: "Completed",
    items: [
      { product: "Sterile Normal Saline 500ml Box (24s)", quantity: 5, unitPrice: "₱1,800.00", subtotal: "₱9,000.00" },
      { product: "Surgical Gloves Medium (100s)", quantity: 10, unitPrice: "₱350.00", subtotal: "₱3,500.00" },
      { product: "Disposable Syringes 5ml (100s)", quantity: 7, unitPrice: "₱850.00", subtotal: "₱5,950.00" },
    ],
  },
];

export const initialSystemLogsData: SystemLog[] = [
  {
    id: 1,
    dateTime: "September 1, 2026, 8:45 PM",
    user: "Juan Dela Cruz",
    role: "Admin",
    action: "Added Product",
    module: "Inventory Management",
    description: "Added Paracetamol 500mg to inventory",
    status: "Success",
    deviceIp: "Desktop – 192.168.1.45",
  },
  {
    id: 2,
    dateTime: "September 1, 2026, 8:50 AM",
    user: "Maria Santos",
    role: "Cashier",
    action: "Login",
    module: "Authentication",
    description: "User logged in to Retail POS Terminal 1",
    status: "Success",
    deviceIp: "POS Terminal 1 – 192.168.1.21",
  },
  {
    id: 3,
    dateTime: "September 1, 2026, 9:15 AM",
    user: "John Cruz",
    role: "Front Desk",
    action: "Sales transactions",
    module: "Wholesale Management",
    description: "Processed Wholesale Purchase Order TRX-0002 for ABC Pharmacy (₱5,250.00)",
    status: "Success",
    deviceIp: "Front Desk PC – 192.168.1.15",
  },
  {
    id: 4,
    dateTime: "September 1, 2026, 9:30 AM",
    user: "Maria Santos",
    role: "Cashier",
    action: "Voided/cancelled transactions",
    module: "Sales POS",
    description: "Voided retail receipt TRX-0003 upon customer cancellation request (₱320.00)",
    status: "Success",
    deviceIp: "POS Terminal 1 – 192.168.1.21",
  },
  {
    id: 5,
    dateTime: "September 1, 2026, 10:15 AM",
    user: "Juan Dela Cruz",
    role: "Admin",
    action: "Failed login attempts",
    module: "Authentication",
    description: 'Invalid credentials entered for account "admin" (Attempt 1 of 3)',
    status: "Failed",
    deviceIp: "Remote Desktop – 192.168.1.105",
  },
  {
    id: 6,
    dateTime: "September 1, 2026, 11:00 AM",
    user: "Juan Dela Cruz",
    role: "Admin",
    action: "Stock adjustments",
    module: "Inventory Management",
    description: "Manual stock recount adjustment for Amoxicillin 500mg: adjusted from 12 to 8 units",
    status: "Success",
    deviceIp: "Admin Tablet – 192.168.1.45",
  },
  {
    id: 7,
    dateTime: "September 1, 2026, 12:00 PM",
    user: "Juan Dela Cruz",
    role: "Admin",
    action: "Backup and restore activities",
    module: "System Settings",
    description: "Automated database backup archive completed and verified (backup_20260901_1200.sql)",
    status: "Success",
    deviceIp: "Server – 127.0.0.1",
  },
];

export const initialUserActivitiesData: UserActivity[] = [
  {
    id: 1,
    dateTime: "Sept. 1, 2026 – 8:30 AM",
    user: "Juan Dela Cruz",
    role: "Admin",
    activity: "Login",
    module: "🔐 Authentication",
    description: "User logged into system dashboard with full administrator privileges",
    flag: "Normal",
  },
  {
    id: 2,
    dateTime: "Sept. 1, 2026 – 8:45 AM",
    user: "Juan Dela Cruz",
    role: "Admin",
    activity: "Product added",
    module: "📦 Inventory Activity",
    description: "Added Paracetamol 500mg to inventory (120 units)",
    flag: "Normal",
  },
  {
    id: 3,
    dateTime: "Sept. 1, 2026 – 8:50 AM",
    user: "Maria Santos",
    role: "Cashier",
    activity: "Login",
    module: "🔐 Authentication",
    description: "Authenticated on POS Terminal 1",
    flag: "Normal",
  },
  {
    id: 4,
    dateTime: "Sept. 1, 2026 – 9:00 AM",
    user: "Maria Santos",
    role: "Cashier",
    activity: "Transaction completed",
    module: "💰 Sales & Wholesale Activity",
    description: "Processed retail cash receipt TRX-0001 (₱450.00)",
    flag: "Normal",
  },
  {
    id: 5,
    dateTime: "Sept. 1, 2026 – 9:15 AM",
    user: "John Cruz",
    role: "Front Desk",
    activity: "Transaction completed",
    module: "💰 Sales & Wholesale Activity",
    description: "Processed wholesale order TRX-0002 for ABC Pharmacy (₱5,250.00)",
    flag: "Normal",
  },
  {
    id: 6,
    dateTime: "Sept. 1, 2026 – 9:30 AM",
    user: "Maria Santos",
    role: "Cashier",
    activity: "Transaction voided",
    module: "💰 Sales & Wholesale Activity",
    description: "Voided retail receipt TRX-0003 after item calculation",
    flag: "Suspicious",
  },
  {
    id: 7,
    dateTime: "Sept. 1, 2026 – 10:15 AM",
    user: "Maria Santos",
    role: "Cashier",
    activity: "Shift review opened",
    module: "💰 Sales & Wholesale Activity",
    description: "Opened Shift Sales and Cash Drawer reconciliation review on POS Terminal 1",
    flag: "Normal",
  },
  {
    id: 8,
    dateTime: "Sept. 1, 2026 – 10:30 AM",
    user: "John Cruz",
    role: "Front Desk",
    activity: "Order dispatched",
    module: "💰 Sales & Wholesale Activity",
    description: "Processed wholesale shipment for Greenfield Care Home",
    flag: "Normal",
  },
  {
    id: 9,
    dateTime: "Sept. 1, 2026 – 11:00 AM",
    user: "Juan Dela Cruz",
    role: "Admin",
    activity: "Stock adjusted",
    module: "📦 Inventory Activity",
    description: "Manual stock recount adjustment for Amoxicillin 500mg (-4 units)",
    flag: "Normal",
  },
  {
    id: 10,
    dateTime: "Sept. 1, 2026 – 12:00 PM",
    user: "Juan Dela Cruz",
    role: "Admin",
    activity: "Backup performed",
    module: "⚙️ System Activity",
    description: "Automated midday database backup completed successfully",
    flag: "Normal",
  },
];
